### ISSUE TITLE
Add a Listener to the change Event 

### ISSUE THREAD

**Issue by mzubairharoon** [ik0r/MVCObject#2]
Hi, it is a great library, I'm implementing it but having some problem, the change the event doesn't fire when the button is clicked, can you highlight the problem.

`

var object_a = new ObjectA();

ObjectA.prototype = new MVCObject();

ObjectA.prototype.foo_changed = function()
{
    console.log('ObjectA foo changed, it is now: ' + this.get('foo'));
};

//	Not working Hook
object_a.changed('foo', () => {
	console.log('===> index.js ===> Need to be Fired');
})

$(function(){

	$('#btn-panel').click(function(){
		
		object_a.set('foo', 'I am cool');
	});
});

`
The attached listener hook doesn't work, can you please tell about it.

Thank you

**Comment by Wyntau** [comment]
@mzubairharoon 
```
object_a.changed = function(key){
console.log('===> index.js ===> Need to be Fired');
})
```

**Comment by mzubairharoon** [comment]
Hi, thank you for your reply, but is it possible to use have two listeners/observer as Google MVCObject provides?

```
google.maps.event.addListenerOnce(object_a, 'foo_changed',
    function() {
        that.set('foo', 'abc foo');
    });
```

**Comment by mzubairharoon** [comment]
I'm looking for something like this, as Google MVC does.

```
object_a.changed('foo', function() {
	console.log('===> First ===> Need to be Fired');
})

object_a.changed('foo', () => {
	console.log('===> Second ===> Need to be Fired');
})

```

is it possible somehow?

Thank you

**Comment by Wyntau** [comment]
@mzubairharoon hi, I recently release mvobject v2.1.3, and now it has already support addListener, addListenerOnce and removeListener
